export const productData = [
  {
    id: 1,
    brand: "VIVO",
    model: "V12 5G",
    series: "V Series",
    img: require("../assets/images/V12.png"),
    price: 999,
    color: "Red",
    storage: "128GB",
    camera: "12MP",
    battery: "3279mAh",
  },
  {
    id: 2,
    brand: "VIVO",
    model: "V30 5G",
    series: "V Series",
    img: require("../assets/images/V30.png"),
    price: 1599,
    color: "Blue",
    storage: "256GB",
    camera: "48MP",
    battery: "3200mAh",
  },
  {
    id: 3,
    brand: "VIVO",
    model: "V90 5G",
    series: "V Series",
    img: require("../assets/images/V90.png"),
    price: 799,
    color: "Green",
    storage: "256GB",
    camera: "50MP",
    battery: "3700mAh",
  },
  {
    id: 4,
    brand: "VIVO",
    model: "X40 5G",
    series: "X Series",
    img: require("../assets/images/X40 5G.png"),
    price: 499,
    color: "Black",
    storage: "128GB",
    camera: "64MP",
    battery: "4500mAh",
  },
  {
    id: 5,
    brand: "VIVO",
    model: "X99 5G",
    series: "X Series",
    img: require("../assets/images/X99.png"),
    price: 599,
    color: "Yellow",
    storage: "128GB",
    camera: "50MP",
    battery: "4355mAh",
  },
  {
    id: 6,
    brand: "VIVO",
    model: " T3 5G",
    series: "T Series",
    img: require("../assets/images/T3 5G.png"),
    price: 449,
    color: "Red",
    storage: "128GB",
    camera: "12.2MP",
    battery: "4410mAh",
  },
  {
    id: 7,
    brand: "VIVO",
    model: " T3x 5G",
    series: "T Series",
    img: require("../assets/images/T3x 5G.png"),
    price: 969,
    color: "Blue",
    storage: "256GB",
    camera: "48MP",
    battery: "4500mAh",
  },
  {
    id: 8,
    brand: "VIVO",
    model: " T4 5G",
    series: "T Series",
    img: require("../assets/images/T4 5G.png"),
    price: 399,
    color: "Green",
    storage: "128GB",
    camera: "50MP",
    battery: "4500mAh",
  },
  {
    id: 9,
    brand: "VIVO",
    model: " T3 5G",
    series: "T Series",
    img: require("../assets/images/T3 5G.png"),
    price: 749,
    color: "Black",
    storage: "256GB",
    camera: "108MP",
    battery: "4600mAh",
  },
  {
    id: 10,
    brand: "VIVO",
    model: " Y99 ",
    series: "Y Series",
    img: require("../assets/images/T3 5G.png"),
    price: 199,
    color: "Yellow",
    storage: "64GB",
    camera: "50MP",
    battery: "5000mAh",
  },
];
